### ISSUE TITLE
QtSql

### ISSUE THREAD

**Issue by fxam** [mkottman/lqt#3]
Hi, I notice that there is no QtSql binding, is this because there already exist a LuaSQL ?
Thanks.

**Comment by mkottman** [comment]
No, the reason was that no one needed it yet :) I enabled it at [this commit](http://github.com/mkottman/lqt/commit/28d714fe424bdb01b43d135e88880befba76c3a2), along with a simple test case. Go ahead and test it out, please  report any bugs.

One thing to note - QtSql uses a lot of QVariant-s, but Lqt doesn't automatically convert values to QVariant - you have to do it explicitly. See the sql_test.lua file for inspiration.
