### ISSUE TITLE
Custom SLOTS?

### ISSUE THREAD

**Issue by zester** [mkottman/lqt#4]
I was wondering how do you do custom slots?

**Comment by mkottman** [comment]
I should write a documentation for Lqt, although you can find some help here: http://code.google.com/p/lqt/w/list and also by looking at the samples in the `test` directory.

In order to create a custom slot on an object, you have to use the `__addmethod` call, as follows:

```
local T = QTableWidget.new(3, 3)
local I = QTableWidgetItem.new()
T:setItem(1, 1, I)
T:__addmethod('changed(QTableWidgetItem*)', function(_, item)
    print('Changed', item, item.__type, item:text():toUtf8(), item:checkState())
end)
T:connect('2itemChanged(QTableWidgetItem*)', T, '1changed(QTableWidgetItem*)')
```

The first parameter to `__addmethod` is the name and signature of the slot you want to create (it should match the signal), and the second argument is the function to be called when such slot is activated. The first parameter of the function is the object whose slot is called (or `self`), and the rest are according to the signature.

You have to be careful about the signature (Qt can be picky), make sure that you check the signature against the result of `__methods` of the object that sends signals, like:

```
for _,m in ipairs(T:__methods()) do print(m) end
```
