### ISSUE TITLE
Qmysql Driver OSX

### ISSUE THREAD

**Issue by usysrc** [mkottman/lqt#50]
I'm trying to the use qtsql module. I'm getting the error when I try to use:

QSqlDatabase.addDatabase("QMYSQL")

QSqlDatabase: QMYSQL driver not loaded
QSqlDatabase: available drivers: QSQLITE QODBC3 QODBC QPSQL7 QPSQL

But I definitely have a libqsqlmysql.dylib available. Do I need to compile another mysql driver for lqt? Any help or hints will be highly appreciated.

**Comment by mkottman** [comment]
Hmm, this is not directly issue with lqt but with your Qt installation. Are you sure it includes QMYSQL driver?

According [to the documentation](http://doc.qt.nokia.com/4.7-snapshot/sql-driver.html#qmysql) you should try to build it yourself on Unix and Mac. It requires the development files for the MySQL client (I think [this is it](http://dev.mysql.com/downloads/connector/c/)).

**Comment by mkottman** [comment]
As per documentation on [plugin deployment](http://doc.qt.nokia.com/4.7-snapshot/deployment-windows.html#qt-plugins), you can use [QCoreApplication::addLibraryPath(const QString &path)](http://doc.qt.nokia.com/4.7-snapshot/qcoreapplication.html#addLibraryPath) to add path to your existing libqsqlmysql.dylib . In lqt, you can try this:

```
QCoreApplication.addLibraryPath('/path/to/plugindir')
```

And see if it finds your module. If not, try creating a simple C++ Qt application to see if the problem is in lqt or in the deployment of your library.
